# Generated by Django 4.2.16 on 2025-06-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0008_auto_20210430_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='staging_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagings', to='adminconsole.app'),
        ),
        migrations.AlterField(
            model_name='app',
            name='git_clone_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='github'),
        ),
    ]
