# Generated by Django 5.2.13 on 2026-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0012_alter_app_python_version_alter_app_version_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='juntagrico_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='juntagrico'),
        ),
    ]
